//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profesionales
    {
        public int Id { get; set; }
        public string NombrePro { get; set; }
        public string ApellidosPro { get; set; }
        public string UserMailPro { get; set; }
        public string UserNamePro { get; set; }
        public string MailContacto { get; set; }
        public string TelfPro { get; set; }
        public string NombreEmp { get; set; }
        public string ServicioTot { get; set; }
        public System.TimeSpan HoraCom { get; set; }
        public System.TimeSpan HoraFin { get; set; }
        public string PassPro { get; set; }
        public string Imagenes { get; set; }
        public int CodCatPro { get; set; }
    }
}
